apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"
rules:
- apiGroups:
  - fpga.intel.com
  resources:
  - '*'
  - n3000nodes
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsync
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tsync
subjects:
- kind: ServiceAccount
  name: tsync
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: tsync
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tsync
subjects:
- kind: ServiceAccount
  name: tsync
  namespace: "{{ .Release.Namespace }}"
#userNames:
#- system:serviceaccount:{{ .Release.Namespace }}:tsync
