apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tsync
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tsync
subjects:
- kind: ServiceAccount
  name: tsync
  namespace: "{{ .Release.Namespace }}"
#userNames:
#- system:serviceaccount:{{ .Release.Namespace }}:tsync
