{{- if .Values.EnableGPS -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "node.gps.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    sts.silicom.com/svc: gpsd
spec:
  type: ClusterIP
  selector:
    app: {{ template "node.gps.name" . }}
  ports:
    - protocol: TCP
      port: {{.Values.GpsSvcPort}}
      targetPort: {{.Values.GpsSvcPort}}

---
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "node.grpc.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    sts.silicom.com/svc: tsyncd
spec:
  type: ClusterIP
  selector:
    app: {{ template "node.grpc.name" . }}
  ports:
    - protocol: TCP
      port: {{.Values.GrpcSvcPort}}
      targetPort: {{.Values.GrpcSvcPort}}      
    - protocol: TCP
      port: {{.Values.GrpcEvntPort}}
      targetPort: {{.Values.GrpcEvntPort}}
    - protocol: TCP
      port: {{.Values.GrpcCfgPort}}
      targetPort: {{.Values.GrpcCfgPort}}
    - protocol: TCP
      port: {{.Values.GrpcStatPort}}
      targetPort: {{.Values.GrpcStatPort}}      
